"""Add profile avatar field

Revision ID: a3eb7c9ffbd4
Revises: a7ab8c9ffbc3
Create Date: 2025-11-06 17:41:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3eb7c9ffbd4'
down_revision = 'a7ab8c9ffbc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar_url')
    # ### end Alembic commands ###