"""Create initial user table

Revision ID: c375c13dbfd0
Revises: 33b9b376d90a
Create Date: 2025-11-03 15:44:26.444920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c375c13dbfd0'
down_revision = '33b9b376d90a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
