"""Initial database schema

Revision ID: ea344e84dfd2
Revises: a7ab8c9ffbc3
Create Date: 2025-11-05 15:27:42.549466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea344e84dfd2'
down_revision = 'a7ab8c9ffbc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
